export type KanaWord = {
  kana: string;
  romaji: string;
  alternatives?: string[];
  translation: string;
};

export const WORDS: KanaWord[] = [
  { kana: "あさ", romaji: "asa", translation: "morning" },
  { kana: "いえ", romaji: "ie", translation: "house" },
  { kana: "うみ", romaji: "umi", translation: "sea" },
  { kana: "えき", romaji: "eki", translation: "station" },
  { kana: "おと", romaji: "oto", translation: "sound" },
  { kana: "かお", romaji: "kao", translation: "face" },
  { kana: "きた", romaji: "kita", translation: "north" },
  { kana: "くも", romaji: "kumo", translation: "cloud" },
  { kana: "けさ", romaji: "kesa", translation: "this morning" },
  { kana: "こころ", romaji: "kokoro", translation: "heart" },
  { kana: "さかな", romaji: "sakana", translation: "fish" },
  { kana: "しお", romaji: "shio", alternatives: ["sio"], translation: "salt" },
  { kana: "すし", romaji: "sushi", alternatives: ["susi"], translation: "sushi" },
  { kana: "せかい", romaji: "sekai", translation: "world" },
  { kana: "そら", romaji: "sora", translation: "sky" },
  { kana: "たまご", romaji: "tamago", translation: "egg" },
  { kana: "ちず", romaji: "chizu", alternatives: ["tizu"], translation: "map" },
  { kana: "つき", romaji: "tsuki", alternatives: ["tuki"], translation: "moon" },
  { kana: "てがみ", romaji: "tegami", translation: "letter" },
  { kana: "とけい", romaji: "tokei", translation: "clock" },
  { kana: "なつ", romaji: "natsu", alternatives: ["natu"], translation: "summer" },
  { kana: "にく", romaji: "niku", translation: "meat" },
  { kana: "ぬの", romaji: "nuno", translation: "cloth" },
  { kana: "ねこ", romaji: "neko", translation: "cat" },
  { kana: "のり", romaji: "nori", translation: "seaweed" },
  { kana: "はな", romaji: "hana", translation: "flower" },
  { kana: "ひかり", romaji: "hikari", translation: "light" },
  { kana: "ふゆ", romaji: "fuyu", alternatives: ["huyu"], translation: "winter" },
  { kana: "へや", romaji: "heya", translation: "room" },
  { kana: "ほし", romaji: "hoshi", alternatives: ["hosi"], translation: "star" },
  { kana: "まど", romaji: "mado", translation: "window" },
  { kana: "みず", romaji: "mizu", translation: "water" },
  { kana: "むし", romaji: "mushi", alternatives: ["musi"], translation: "insect" },
  { kana: "め", romaji: "me", translation: "eye" },
  { kana: "もり", romaji: "mori", translation: "forest" },
  { kana: "やま", romaji: "yama", translation: "mountain" },
  { kana: "ゆき", romaji: "yuki", translation: "snow" },
  { kana: "よる", romaji: "yoru", translation: "night" },
  { kana: "らいねん", romaji: "rainen", translation: "next year" },
  { kana: "りんご", romaji: "ringo", translation: "apple" },
  { kana: "るす", romaji: "rusu", translation: "absence" },
  { kana: "れきし", romaji: "rekishi", alternatives: ["rekisi"], translation: "history" },
  { kana: "ろく", romaji: "roku", translation: "six" },
  { kana: "わたし", romaji: "watashi", alternatives: ["watasi"], translation: "I / me" },
  { kana: "ほん", romaji: "hon", translation: "book" },
  { kana: "でんしゃ", romaji: "densha", translation: "train" },
  { kana: "きょう", romaji: "kyou", translation: "today" },
  { kana: "がっこう", romaji: "gakkou", translation: "school" },
  { kana: "りょこう", romaji: "ryokou", translation: "travel" },
  { kana: "ちょっと", romaji: "chotto", alternatives: ["tyotto"], translation: "a little" },
  { kana: "おちゃ", romaji: "ocha", translation: "tea" },
  { kana: "しゃしん", romaji: "shashin", alternatives: ["syasin"], translation: "photograph" },
  { kana: "こと", romaji: "koto", translation: "thing / matter" },
  { kana: "もの", romaji: "mono", translation: "thing / object" },
  { kana: "ひと", romaji: "hito", translation: "person" },
  { kana: "こども", romaji: "kodomo", translation: "child" },
  { kana: "おとな", romaji: "otona", translation: "adult" },
  { kana: "おとこ", romaji: "otoko", translation: "man" },
  { kana: "おんな", romaji: "onna", translation: "woman" },
  { kana: "ともだち", romaji: "tomodachi", translation: "friend" },
  { kana: "かぞく", romaji: "kazoku", translation: "family" },
  { kana: "ちち", romaji: "chichi", translation: "father" },
  { kana: "はは", romaji: "haha", translation: "mother" },
  { kana: "あに", romaji: "ani", translation: "older brother" },
  { kana: "あね", romaji: "ane", translation: "older sister" },
  { kana: "おとうと", romaji: "otouto", translation: "younger brother" },
  { kana: "いもうと", romaji: "imouto", translation: "younger sister" },
  { kana: "せんせい", romaji: "sensei", translation: "teacher" },
  { kana: "がくせい", romaji: "gakusei", translation: "student" },
  { kana: "かいしゃ", romaji: "kaisha", translation: "company" },
  { kana: "しごと", romaji: "shigoto", translation: "work" },
  { kana: "みせ", romaji: "mise", translation: "shop" },
  { kana: "くに", romaji: "kuni", translation: "country" },
  { kana: "まち", romaji: "machi", translation: "town" },
  { kana: "むら", romaji: "mura", translation: "village" },
  { kana: "みち", romaji: "michi", translation: "road" },
  { kana: "こうえん", romaji: "kouen", translation: "park" },
  { kana: "びょういん", romaji: "byouin", translation: "hospital" },
  { kana: "ぎんこう", romaji: "ginkou", translation: "bank" },
  { kana: "ゆうびんきょく", romaji: "yuubinkyoku", translation: "post office" },
  { kana: "としょかん", romaji: "toshokan", translation: "library" },
  { kana: "きっさてん", romaji: "kissaten", translation: "coffee shop" },
  { kana: "ごはん", romaji: "gohan", translation: "rice / meal" },
  { kana: "ぱん", romaji: "pan", translation: "bread" },
  { kana: "うどん", romaji: "udon", translation: "udon noodles" },
  { kana: "そば", romaji: "soba", translation: "soba noodles" },
  { kana: "みそ", romaji: "miso", translation: "miso" },
  { kana: "しょうゆ", romaji: "shouyu", translation: "soy sauce" },
  { kana: "さとう", romaji: "satou", translation: "sugar" },
  { kana: "やさい", romaji: "yasai", translation: "vegetables" },
  { kana: "くだもの", romaji: "kudamono", translation: "fruit" },
  { kana: "みかん", romaji: "mikan", translation: "mandarin orange" },
  { kana: "いちご", romaji: "ichigo", translation: "strawberry" },
  { kana: "ぶどう", romaji: "budou", translation: "grapes" },
  { kana: "もも", romaji: "momo", translation: "peach" },
  { kana: "なし", romaji: "nashi", translation: "pear" },
  { kana: "すいか", romaji: "suika", translation: "watermelon" },
  { kana: "にんじん", romaji: "ninjin", translation: "carrot" },
  { kana: "たまねぎ", romaji: "tamanegi", translation: "onion" },
  { kana: "じゃがいも", romaji: "jagaimo", translation: "potato" },
  { kana: "だいこん", romaji: "daikon", translation: "daikon radish" },
  { kana: "きゅうり", romaji: "kyuuri", translation: "cucumber" },
  { kana: "きのこ", romaji: "kinoko", translation: "mushroom" },
  { kana: "ぎゅうにく", romaji: "gyuuniku", translation: "beef" },
  { kana: "ぶたにく", romaji: "butaniku", translation: "pork" },
  { kana: "とりにく", romaji: "toriniku", translation: "chicken" },
  { kana: "こめ", romaji: "kome", translation: "uncooked rice" },
  { kana: "ぎゅうにゅう", romaji: "gyuunyuu", translation: "milk" },
  { kana: "みそしる", romaji: "misoshiru", translation: "miso soup" },
  { kana: "おにぎり", romaji: "onigiri", translation: "rice ball" },
  { kana: "べんとう", romaji: "bentou", translation: "boxed lunch" },
  { kana: "いぬ", romaji: "inu", translation: "dog" },
  { kana: "とり", romaji: "tori", translation: "bird" },
  { kana: "うま", romaji: "uma", translation: "horse" },
  { kana: "うし", romaji: "ushi", translation: "cow" },
  { kana: "ぶた", romaji: "buta", translation: "pig" },
  { kana: "ひつじ", romaji: "hitsuji", translation: "sheep" },
  { kana: "さる", romaji: "saru", translation: "monkey" },
  { kana: "うさぎ", romaji: "usagi", translation: "rabbit" },
  { kana: "ねずみ", romaji: "nezumi", translation: "mouse" },
  { kana: "きつね", romaji: "kitsune", translation: "fox" },
  { kana: "たぬき", romaji: "tanuki", translation: "raccoon dog" },
  { kana: "くま", romaji: "kuma", translation: "bear" },
  { kana: "ぞう", romaji: "zou", translation: "elephant" },
  { kana: "きりん", romaji: "kirin", translation: "giraffe" },
  { kana: "しまうま", romaji: "shimauma", translation: "zebra" },
  { kana: "かえる", romaji: "kaeru", translation: "frog" },
  { kana: "へび", romaji: "hebi", translation: "snake" },
  { kana: "かめ", romaji: "kame", translation: "turtle" },
  { kana: "ちょう", romaji: "chou", translation: "butterfly" },
  { kana: "はち", romaji: "hachi", translation: "bee" },
  { kana: "あり", romaji: "ari", translation: "ant" },
  { kana: "くじら", romaji: "kujira", translation: "whale" },
  { kana: "いるか", romaji: "iruka", translation: "dolphin" },
  { kana: "たこ", romaji: "tako", translation: "octopus" },
  { kana: "えび", romaji: "ebi", translation: "shrimp" },
  { kana: "かに", romaji: "kani", translation: "crab" },
  { kana: "かい", romaji: "kai", translation: "shellfish" },
  { kana: "かわ", romaji: "kawa", translation: "river" },
  { kana: "いけ", romaji: "ike", translation: "pond" },
  { kana: "みずうみ", romaji: "mizuumi", translation: "lake" },
  { kana: "たき", romaji: "taki", translation: "waterfall" },
  { kana: "しま", romaji: "shima", translation: "island" },
  { kana: "はま", romaji: "hama", translation: "beach" },
  { kana: "すな", romaji: "suna", translation: "sand" },
  { kana: "いし", romaji: "ishi", translation: "stone" },
  { kana: "き", romaji: "ki", translation: "tree" },
  { kana: "くさ", romaji: "kusa", translation: "grass" },
  { kana: "はっぱ", romaji: "happa", translation: "leaf" },
  { kana: "えだ", romaji: "eda", translation: "branch" },
  { kana: "たね", romaji: "tane", translation: "seed" },
  { kana: "あたま", romaji: "atama", translation: "head" },
  { kana: "かみ", romaji: "kami", translation: "hair" },
  { kana: "みみ", romaji: "mimi", translation: "ear" },
  { kana: "くち", romaji: "kuchi", translation: "mouth" },
  { kana: "は", romaji: "ha", translation: "tooth" },
  { kana: "した", romaji: "shita", translation: "tongue" },
  { kana: "くび", romaji: "kubi", translation: "neck" },
  { kana: "かた", romaji: "kata", translation: "shoulder" },
  { kana: "うで", romaji: "ude", translation: "arm" },
  { kana: "て", romaji: "te", translation: "hand" },
  { kana: "ゆび", romaji: "yubi", translation: "finger" },
  { kana: "むね", romaji: "mune", translation: "chest" },
  { kana: "おなか", romaji: "onaka", translation: "stomach" },
  { kana: "せなか", romaji: "senaka", translation: "back" },
  { kana: "あし", romaji: "ashi", translation: "foot / leg" },
  { kana: "ひざ", romaji: "hiza", translation: "knee" },
  { kana: "からだ", romaji: "karada", translation: "body" },
  { kana: "こえ", romaji: "koe", translation: "voice" },
  { kana: "ちから", romaji: "chikara", translation: "strength" },
  { kana: "あか", romaji: "aka", translation: "red" },
  { kana: "あお", romaji: "ao", translation: "blue" },
  { kana: "しろ", romaji: "shiro", translation: "white" },
  { kana: "くろ", romaji: "kuro", translation: "black" },
  { kana: "きいろ", romaji: "kiiro", translation: "yellow" },
  { kana: "みどり", romaji: "midori", translation: "green" },
  { kana: "ちゃいろ", romaji: "chairo", translation: "brown" },
  { kana: "いろ", romaji: "iro", translation: "color" },
  { kana: "ふく", romaji: "fuku", translation: "clothes" },
  { kana: "しゃつ", romaji: "shatsu", translation: "shirt" },
  { kana: "ずぼん", romaji: "zubon", translation: "trousers" },
  { kana: "くつ", romaji: "kutsu", translation: "shoes" },
  { kana: "くつした", romaji: "kutsushita", translation: "socks" },
  { kana: "ぼうし", romaji: "boushi", translation: "hat" },
  { kana: "かばん", romaji: "kaban", translation: "bag" },
  { kana: "かさ", romaji: "kasa", translation: "umbrella" },
  { kana: "めがね", romaji: "megane", translation: "glasses" },
  { kana: "きもの", romaji: "kimono", translation: "kimono" },
  { kana: "さいふ", romaji: "saifu", translation: "wallet" },
  { kana: "ぼたん", romaji: "botan", translation: "button" },
  { kana: "てぶくろ", romaji: "tebukuro", translation: "gloves" },
  { kana: "つくえ", romaji: "tsukue", translation: "desk" },
  { kana: "いす", romaji: "isu", translation: "chair" },
  { kana: "たな", romaji: "tana", translation: "shelf" },
  { kana: "ほんだな", romaji: "hondana", translation: "bookshelf" },
  { kana: "ふとん", romaji: "futon", translation: "futon" },
  { kana: "まくら", romaji: "makura", translation: "pillow" },
  { kana: "もうふ", romaji: "moufu", translation: "blanket" },
  { kana: "でんき", romaji: "denki", translation: "electricity / light" },
  { kana: "でんわ", romaji: "denwa", translation: "telephone" },
  { kana: "けいたい", romaji: "keitai", translation: "mobile phone" },
  { kana: "てれび", romaji: "terebi", translation: "television" },
  { kana: "らじお", romaji: "rajio", translation: "radio" },
  { kana: "かぎ", romaji: "kagi", translation: "key" },
  { kana: "はこ", romaji: "hako", translation: "box" },
  { kana: "びん", romaji: "bin", translation: "bottle" },
  { kana: "さら", romaji: "sara", translation: "plate" },
  { kana: "ちゃわん", romaji: "chawan", translation: "rice bowl" },
  { kana: "はし", romaji: "hashi", translation: "chopsticks" },
  { kana: "なべ", romaji: "nabe", translation: "cooking pot" },
  { kana: "やかん", romaji: "yakan", translation: "kettle" },
  { kana: "れいぞうこ", romaji: "reizouko", translation: "refrigerator" },
  { kana: "せんたくき", romaji: "sentakuki", translation: "washing machine" },
  { kana: "そうじき", romaji: "soujiki", translation: "vacuum cleaner" },
  { kana: "と", romaji: "to", translation: "door" },
  { kana: "げんかん", romaji: "genkan", translation: "entryway" },
  { kana: "だいどころ", romaji: "daidokoro", translation: "kitchen" },
  { kana: "おふろ", romaji: "ofuro", translation: "bath" },
  { kana: "にわ", romaji: "niwa", translation: "garden" },
  { kana: "かいだん", romaji: "kaidan", translation: "stairs" },
  { kana: "やね", romaji: "yane", translation: "roof" },
  { kana: "いま", romaji: "ima", translation: "now" },
  { kana: "きのう", romaji: "kinou", translation: "yesterday" },
  { kana: "あした", romaji: "ashita", translation: "tomorrow" },
  { kana: "おととい", romaji: "ototoi", translation: "day before yesterday" },
  { kana: "あさって", romaji: "asatte", translation: "day after tomorrow" },
  { kana: "まいにち", romaji: "mainichi", translation: "every day" },
  { kana: "まいあさ", romaji: "maiasa", translation: "every morning" },
  { kana: "まいばん", romaji: "maiban", translation: "every evening" },
  { kana: "ひる", romaji: "hiru", translation: "noon" },
  { kana: "ばん", romaji: "ban", translation: "evening" },
  { kana: "よなか", romaji: "yonaka", translation: "midnight" },
  { kana: "しゅう", romaji: "shuu", translation: "week" },
  { kana: "とし", romaji: "toshi", translation: "year" },
  { kana: "はる", romaji: "haru", translation: "spring" },
  { kana: "あき", romaji: "aki", translation: "autumn" },
  { kana: "はれ", romaji: "hare", translation: "clear weather" },
  { kana: "あめ", romaji: "ame", translation: "rain" },
  { kana: "くもり", romaji: "kumori", translation: "cloudy weather" },
  { kana: "かぜ", romaji: "kaze", translation: "wind" },
  { kana: "たいよう", romaji: "taiyou", translation: "sun" },
  { kana: "きおん", romaji: "kion", translation: "temperature" },
  { kana: "てんき", romaji: "tenki", translation: "weather" },
  { kana: "じかん", romaji: "jikan", translation: "time" },
  { kana: "ふん", romaji: "fun", translation: "minute" },
  { kana: "はん", romaji: "han", translation: "half" },
  { kana: "げつようび", romaji: "getsuyoubi", translation: "Monday" },
  { kana: "かようび", romaji: "kayoubi", translation: "Tuesday" },
  { kana: "すいようび", romaji: "suiyoubi", translation: "Wednesday" },
  { kana: "もくようび", romaji: "mokuyoubi", translation: "Thursday" },
  { kana: "きんようび", romaji: "kinyoubi", translation: "Friday" },
  { kana: "どようび", romaji: "doyoubi", translation: "Saturday" },
  { kana: "たべる", romaji: "taberu", translation: "to eat" },
  { kana: "のむ", romaji: "nomu", translation: "to drink" },
  { kana: "みる", romaji: "miru", translation: "to see" },
  { kana: "きく", romaji: "kiku", translation: "to listen / ask" },
  { kana: "はなす", romaji: "hanasu", translation: "to speak" },
  { kana: "よむ", romaji: "yomu", translation: "to read" },
  { kana: "かく", romaji: "kaku", translation: "to write" },
  { kana: "いく", romaji: "iku", translation: "to go" },
  { kana: "くる", romaji: "kuru", translation: "to come" },
  { kana: "もどる", romaji: "modoru", translation: "to return" },
  { kana: "ねる", romaji: "neru", translation: "to sleep" },
  { kana: "おきる", romaji: "okiru", translation: "to wake up" },
  { kana: "ある", romaji: "aru", translation: "to exist" },
  { kana: "いる", romaji: "iru", translation: "to be / exist" },
  { kana: "する", romaji: "suru", translation: "to do" },
  { kana: "あそぶ", romaji: "asobu", translation: "to play" },
  { kana: "まつ", romaji: "matsu", translation: "to wait" },
  { kana: "あう", romaji: "au", translation: "to meet" },
  { kana: "かう", romaji: "kau", translation: "to buy" },
  { kana: "うる", romaji: "uru", translation: "to sell" },
  { kana: "つくる", romaji: "tsukuru", translation: "to make" },
  { kana: "つかう", romaji: "tsukau", translation: "to use" },
  { kana: "あける", romaji: "akeru", translation: "to open" },
  { kana: "しめる", romaji: "shimeru", translation: "to close" },
  { kana: "はいる", romaji: "hairu", translation: "to enter" },
  { kana: "でる", romaji: "deru", translation: "to leave" },
  { kana: "すわる", romaji: "suwaru", translation: "to sit" },
  { kana: "たつ", romaji: "tatsu", translation: "to stand" },
  { kana: "あるく", romaji: "aruku", translation: "to walk" },
  { kana: "はしる", romaji: "hashiru", translation: "to run" },
  { kana: "およぐ", romaji: "oyogu", translation: "to swim" },
  { kana: "うたう", romaji: "utau", translation: "to sing" },
  { kana: "わらう", romaji: "warau", translation: "to laugh" },
  { kana: "なく", romaji: "naku", translation: "to cry" },
  { kana: "おもう", romaji: "omou", translation: "to think" },
  { kana: "しる", romaji: "shiru", translation: "to know" },
  { kana: "わかる", romaji: "wakaru", translation: "to understand" },
  { kana: "おしえる", romaji: "oshieru", translation: "to teach" },
  { kana: "ならう", romaji: "narau", translation: "to learn" },
  { kana: "はたらく", romaji: "hataraku", translation: "to work" },
  { kana: "やすむ", romaji: "yasumu", translation: "to rest" },
  { kana: "あらう", romaji: "arau", translation: "to wash" },
  { kana: "きる", romaji: "kiru", translation: "to wear" },
  { kana: "ぬぐ", romaji: "nugu", translation: "to take off" },
  { kana: "あつい", romaji: "atsui", translation: "hot" },
  { kana: "さむい", romaji: "samui", translation: "cold" },
  { kana: "おおきい", romaji: "ookii", translation: "big" },
  { kana: "ちいさい", romaji: "chiisai", translation: "small" },
];

export function randomWord(except?: string, excluded: ReadonlySet<string> = new Set()) {
  const candidates = WORDS.filter((word) => word.kana !== except && !excluded.has(word.kana));
  const pool = candidates.length ? candidates : WORDS.filter((word) => word.kana !== except);
  return pool[Math.floor(Math.random() * pool.length)];
}
